# Generated by Django 5.2.14 on 2026-06-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='使用者',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('姓名', models.CharField(max_length=50, verbose_name='姓名')),
                ('電郵', models.EmailField(max_length=254, unique=True, verbose_name='電郵')),
                ('電話', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('建立時間', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
            },
        ),
        migrations.CreateModel(
            name='產品',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('產品名稱', models.CharField(max_length=100, verbose_name='產品名稱')),
                ('價格', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='價格')),
                ('庫存', models.IntegerField(default=0, verbose_name='庫存')),
                ('描述', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '產品',
                'verbose_name_plural': '產品',
            },
        ),
        migrations.CreateModel(
            name='訂單',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('數量', models.IntegerField(default=1, verbose_name='數量')),
                ('訂單時間', models.DateTimeField(auto_now_add=True, verbose_name='訂單時間')),
                ('產品', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.產品', verbose_name='產品')),
                ('購買者', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.使用者', verbose_name='購買者')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
            },
        ),
    ]
