# Generated by Django 5.2.14 on 2026-06-14 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('inspection', '強制驗窗'), ('repair', '鋁窗維修'), ('waterproof', '防水工程')], max_length=20)),
                ('booking_date', models.DateField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待處理'), ('completed', '已完成')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qp_name', models.CharField(max_length=50)),
                ('result', models.TextField()),
                ('is_safe', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.order')),
            ],
        ),
    ]
